# -*- coding: utf-8 -*-
"""FAQ content (visible accordion + FAQPage JSON-LD). FAQ = English pairs;
FAQ_T[code] = translated pairs in the same order. No double-quotes or & in values."""

FAQ = [
    ("Which AI models does the robot support?",
     "Out of the box it supports modern vision-language-action and imitation-learning policies, including Pi0, Pi0.5, ACT, and SmolVLA. Collect teleoperation data, fine-tune on a consumer GPU, and deploy through the SDK."),
    ("What is included with the robot?",
     "Every unit ships with the full SDK and a simple REST API, a URDF model, a bundled simulator, head-mounted stereo plus wrist cameras, grippers, and direct engineering support. The teleoperation pipeline works on day one."),
    ("Can I collect teleoperation data and train policies myself?",
     "Yes. Teleoperate via VR with a Meta Quest 3S or a leader-follower controller, record demonstrations in the standard dataset format, and train ACT or fine-tune a vision-language-action model on a single consumer GPU."),
    ("What compute does the robot run on?",
     "Onboard compute is a Raspberry Pi 5 or an NVIDIA Jetson. Lightweight policies run on-device, while heavier vision-language-action models can run on a tethered workstation GPU and stream commands over the REST API."),
    ("Is the robot modular?",
     "Yes. You can swap arms, grippers (2-finger, 4-finger, or advanced five-finger hands), and base modules such as legs or wheels, and adapt the platform to your task rather than the other way around."),
    ("Where is the robot made?",
     "Prometheus is designed and manufactured in the European Union, which matters for European research labs and companies that care about supply-chain provenance, support, and data sovereignty."),
]

FAQ_T = {
    "bg": [
        ("Кои AI модели поддържа роботът?",
         "В готов вид той поддържа съвременни политики от тип зрение-език-действие и имитационно обучение, включително Pi0, Pi0.5, ACT и SmolVLA. Събирайте данни от телеоперация, дообучавайте на потребителски GPU и внедрявайте чрез SDK."),
        ("Какво е включено с робота?",
         "Всяка единица се доставя с пълния SDK и опростен REST API, URDF модел, вграден симулатор, монтирани на главата стерео камери заедно с камери на китките, захвати и пряка инженерна поддръжка. Конвейерът за телеоперация работи още от първия ден."),
        ("Мога ли сам да събирам данни от телеоперация и да обучавам политики?",
         "Да. Управлявайте дистанционно чрез VR с Meta Quest 3S или с контролер от тип водач-последовател, записвайте демонстрации в стандартния формат на набора от данни и обучавайте ACT или дообучавайте модел зрение-език-действие на един потребителски GPU."),
        ("На какъв изчислителен ресурс работи роботът?",
         "Бордовият изчислителен модул е Raspberry Pi 5 или NVIDIA Jetson. Леките политики се изпълняват на самото устройство, докато по-тежките модели зрение-език-действие могат да работят на GPU в свързана работна станция и да предават команди през REST API."),
        ("Модулен ли е роботът?",
         "Да. Можете да сменяте ръце, захвати (с 2 пръста, с 4 пръста или усъвършенствани ръце с пет пръста) и базови модули като крака или колела, и да адаптирате платформата към вашата задача, вместо обратното."),
        ("Къде се произвежда роботът?",
         "Prometheus е проектиран и произведен в Европейския съюз, което има значение за европейските изследователски лаборатории и компании, които държат на произхода на веригата за доставки, поддръжката и суверенитета на данните."),
    ],
    "cs": [
        ("Které modely AI robot podporuje?",
         "Ihned po vybalení podporuje moderní postupy typu vision-language-action a imitační učení, včetně Pi0, Pi0.5, ACT a SmolVLA. Shromážděte data z teleoperace, dolaďte je na běžné spotřebitelské GPU a nasaďte prostřednictvím SDK."),
        ("Co je součástí dodávky robota?",
         "Každá jednotka se dodává s kompletním SDK a jednoduchým REST API, modelem URDF, integrovaným simulátorem, stereokamerou umístěnou na hlavě i kamerami na zápěstí, chapadly a přímou inženýrskou podporou. Pipeline pro teleoperaci funguje od prvního dne."),
        ("Mohu sám shromažďovat data z teleoperace a trénovat vlastní postupy?",
         "Ano. Ovládejte robota dálkově prostřednictvím VR se zařízením Meta Quest 3S nebo pomocí ovladače typu leader-follower, zaznamenávejte ukázky ve standardním formátu datové sady a trénujte ACT nebo dolaďte model vision-language-action na jediném spotřebitelském GPU."),
        ("Na jakém výpočetním hardwaru robot běží?",
         "Palubní výpočetní jednotkou je Raspberry Pi 5 nebo NVIDIA Jetson. Nenáročné postupy běží přímo na zařízení, zatímco náročnější modely vision-language-action mohou běžet na připojené pracovní stanici s GPU a přenášet příkazy přes REST API."),
        ("Je robot modulární?",
         "Ano. Můžete vyměnit ramena, chapadla (dvouprstá, čtyřprstá nebo pokročilé pětiprsté ruce) a základní moduly, jako jsou nohy či kola, a přizpůsobit platformu vašemu úkolu, nikoli naopak."),
        ("Kde se robot vyrábí?",
         "Prometheus je navržen a vyráběn v Evropské unii, což má význam pro evropské výzkumné laboratoře a společnosti, kterým záleží na původu dodavatelského řetězce, podpoře a datové suverenitě."),
    ],
    "da": [
        ("Hvilke AI-modeller understøtter robotten?",
         "Lige ud af kassen understøtter den moderne vision-language-action- og imitationslæringspolitikker, herunder Pi0, Pi0.5, ACT og SmolVLA. Indsaml teleoperationsdata, finjuster på en forbruger-GPU, og udrul via SDK."),
        ("Hvad er inkluderet med robotten?",
         "Hver enhed leveres med det fulde SDK og et enkelt REST API, en URDF-model, en medfølgende simulator, hovedmonterede stereokameraer plus håndledskameraer, gribere og direkte teknisk support. Teleoperationspipelinen fungerer fra første dag."),
        ("Kan jeg selv indsamle teleoperationsdata og træne politikker?",
         "Ja. Teleoperer via VR med en Meta Quest 3S eller en leder-følger-controller, optag demonstrationer i standarddatasætformatet, og træn ACT eller finjuster en vision-language-action-model på en enkelt forbruger-GPU."),
        ("Hvilken beregningskraft kører robotten på?",
         "Den indbyggede beregningskraft er en Raspberry Pi 5 eller en NVIDIA Jetson. Lette politikker kører på enheden, mens tungere vision-language-action-modeller kan køre på en tilsluttet arbejdsstations-GPU og streame kommandoer via REST API."),
        ("Er robotten modulær?",
         "Ja. Du kan udskifte arme, gribere (2-finger, 4-finger eller avancerede femfingrede hænder) og basismoduler såsom ben eller hjul, og tilpasse platformen til din opgave i stedet for omvendt."),
        ("Hvor er robotten fremstillet?",
         "Prometheus er designet og fremstillet i Den Europæiske Union, hvilket har betydning for europæiske forskningslaboratorier og virksomheder, der lægger vægt på forsyningskædens oprindelse, support og datasuverænitet."),
    ],
    "de": [
        ("Welche KI-Modelle unterstützt der Roboter?",
         "Ab Werk unterstützt er moderne Vision-Language-Action- und Imitation-Learning-Policies, darunter Pi0, Pi0.5, ACT und SmolVLA. Sammeln Sie Teleoperationsdaten, feintunen Sie auf einer Consumer-GPU und deployen Sie über das SDK."),
        ("Was ist im Lieferumfang des Roboters enthalten?",
         "Jede Einheit wird mit dem vollständigen SDK und einer einfachen REST-API, einem URDF-Modell, einem mitgelieferten Simulator, kopfmontierter Stereokamera plus Handgelenkkameras, Greifern und direktem Engineering-Support geliefert. Die Teleoperation funktioniert ab dem ersten Tag."),
        ("Kann ich selbst Teleoperationsdaten sammeln und Policies trainieren?",
         "Ja. Teleoperieren Sie per VR mit einer Meta Quest 3S oder einem Leader-Follower-Controller, zeichnen Sie Demonstrationen im Standard-Datensatzformat auf und trainieren Sie ACT oder feintunen Sie ein Vision-Language-Action-Modell auf einer einzigen Consumer-GPU."),
        ("Auf welcher Recheneinheit läuft der Roboter?",
         "Die Onboard-Recheneinheit ist ein Raspberry Pi 5 oder ein NVIDIA Jetson. Leichte Policies laufen auf dem Gerät, während größere Vision-Language-Action-Modelle auf einer angebundenen Workstation-GPU laufen und Befehle über die REST-API streamen können."),
        ("Ist der Roboter modular?",
         "Ja. Sie können Arme, Greifer (2-Finger, 4-Finger oder fortschrittliche Fünf-Finger-Hände) und Basismodule wie Beine oder Räder austauschen und die Plattform an Ihre Aufgabe anpassen statt umgekehrt."),
        ("Wo wird der Roboter hergestellt?",
         "Prometheus wird in der Europäischen Union entworfen und gefertigt, was für europäische Forschungslabore und Unternehmen wichtig ist, denen Lieferketten-Herkunft, Support und Datensouveränität am Herzen liegen."),
    ],
    "es": [
        ("¿Qué modelos de IA admite el robot?",
         "De fábrica admite políticas modernas de visión-lenguaje-acción y de aprendizaje por imitación, incluyendo Pi0, Pi0.5, ACT y SmolVLA. Recopile datos de teleoperación, ajústelos en una GPU de consumo e impleméntelos a través del SDK."),
        ("¿Qué se incluye con el robot?",
         "Cada unidad se entrega con el SDK completo y una sencilla REST API, un modelo URDF, un simulador integrado, cámaras estéreo montadas en la cabeza más cámaras en la muñeca, pinzas y soporte de ingeniería directo. La canalización de teleoperación funciona desde el primer día."),
        ("¿Puedo recopilar datos de teleoperación y entrenar políticas por mi cuenta?",
         "Sí. Teleopere mediante VR con un Meta Quest 3S o un controlador líder-seguidor, registre demostraciones en el formato de conjunto de datos estándar, y entrene ACT o ajuste un modelo de visión-lenguaje-acción en una sola GPU de consumo."),
        ("¿Con qué cómputo funciona el robot?",
         "El cómputo a bordo es una Raspberry Pi 5 o una NVIDIA Jetson. Las políticas ligeras se ejecutan en el dispositivo, mientras que los modelos de visión-lenguaje-acción más pesados pueden ejecutarse en la GPU de una estación de trabajo conectada y transmitir comandos a través de la REST API."),
        ("¿Es modular el robot?",
         "Sí. Puede intercambiar brazos, pinzas (de 2 dedos, de 4 dedos o manos avanzadas de cinco dedos) y módulos de base como piernas o ruedas, y adaptar la plataforma a su tarea en lugar de lo contrario."),
        ("¿Dónde se fabrica el robot?",
         "Prometheus se diseña y fabrica en la Unión Europea, lo cual es importante para los laboratorios de investigación y las empresas europeas que valoran la procedencia de la cadena de suministro, el soporte y la soberanía de los datos."),
    ],
    "et": [
        ("Milliseid tehisintellekti mudeleid robot toetab?",
         "Karbist väljas toetab see kaasaegseid nägemis-keele-tegevuse ja imiteerival õppimisel põhinevaid poliitikaid, sealhulgas Pi0, Pi0.5, ACT ja SmolVLA. Koguge teleopereerimise andmeid, peenhäälestage tarbija GPU peal ja juurutage SDK kaudu."),
        ("Mis robotiga kaasas on?",
         "Iga seade tarnitakse koos täisvaliku SDK ja lihtsa REST API-ga, URDF-mudeliga, kaasasoleva simulaatoriga, pähe kinnitatava stereokaamera ning rannekaameratega, haaratsitega ja otsese inseneritoega. Teleopereerimise töövoog toimib esimesest päevast alates."),
        ("Kas saan teleopereerimise andmeid ise koguda ja poliitikaid treenida?",
         "Jah. Teleopereerige VR kaudu Meta Quest 3S seadme või juht-järgija kontrolleriga, salvestage demonstratsioonid standardses andmestiku vormingus ning treenige ACT või peenhäälestage nägemis-keele-tegevuse mudel ühel tarbija GPU-l."),
        ("Millisel arvutusvõimsusel robot töötab?",
         "Pardal olev arvutusvõimsus on Raspberry Pi 5 või NVIDIA Jetson. Kerged poliitikad töötavad seadmes endas, samas kui raskemad nägemis-keele-tegevuse mudelid saavad töötada ühendatud tööjaama GPU-l ja edastada käske REST API kaudu."),
        ("Kas robot on moodulpõhine?",
         "Jah. Saate vahetada käsivarsi, haaratseid (2-sõrmelisi, 4-sõrmelisi või täiustatud viiesõrmelisi käsi) ning baasmooduleid nagu jalad või rattad, ning kohandada platvormi oma ülesandele, mitte vastupidi."),
        ("Kus robot valmistatakse?",
         "Prometheus on projekteeritud ja toodetud Euroopa Liidus, mis on oluline Euroopa uurimislaboritele ja ettevõtetele, kes hoolivad tarneahela päritolust, toest ja andmesuveräänsusest."),
    ],
    "fi": [
        ("Mitä tekoälymalleja robotti tukee?",
         "Heti käyttövalmiina se tukee nykyaikaisia näkö-kieli-toiminta- ja imitaatio-oppimismalleja, mukaan lukien Pi0, Pi0.5, ACT ja SmolVLA. Kerää teleoperaatiodataa, hienosäädä kuluttajatason GPU:lla ja ota käyttöön SDK:n kautta."),
        ("Mitä robotin mukana tulee?",
         "Jokainen yksikkö toimitetaan täydellä SDK:lla ja yksinkertaisella REST API:lla, URDF-mallilla, mukana tulevalla simulaattorilla, päähän kiinnitettävillä stereo- sekä rannekameroilla, tarttujilla ja suoralla insinöörituella. Teleoperaatioputki toimii ensimmäisestä päivästä alkaen."),
        ("Voinko kerätä teleoperaatiodataa ja kouluttaa malleja itse?",
         "Kyllä. Teleoperoi VR-lasien avulla Meta Quest 3S -laitteella tai johtaja-seuraaja-ohjaimella, tallenna demonstraatiot standardissa datajoukkomuodossa ja kouluta ACT tai hienosäädä näkö-kieli-toimintamalli yhdellä kuluttajatason GPU:lla."),
        ("Millä laskentateholla robotti toimii?",
         "Sisäänrakennettu laskentateho on Raspberry Pi 5 tai NVIDIA Jetson. Kevyet mallit toimivat laitteessa, kun taas raskaammat näkö-kieli-toimintamallit voivat toimia kytketyn työaseman GPU:lla ja välittää komennot REST API:n kautta."),
        ("Onko robotti modulaarinen?",
         "Kyllä. Voit vaihtaa käsivarsia, tarttujia (2-sormisia, 4-sormisia tai edistyneitä viisisormisia käsiä) sekä perusmoduuleja kuten jalkoja tai pyöriä, ja mukauttaa alustan tehtävääsi sopivaksi eikä toisin päin."),
        ("Missä robotti valmistetaan?",
         "Prometheus on suunniteltu ja valmistettu Euroopan unionissa, mikä on merkityksellistä eurooppalaisille tutkimuslaboratorioille ja yrityksille, jotka välittävät toimitusketjun alkuperästä, tuesta ja datan suvereniteetista."),
    ],
    "fr": [
        ("Quels modèles d'IA le robot prend-il en charge ?",
         "Dès le départ, il prend en charge les politiques modernes de type vision-language-action et d'apprentissage par imitation, dont Pi0, Pi0.5, ACT et SmolVLA. Collectez des données de téléopération, affinez sur un GPU grand public et déployez via le SDK."),
        ("Qu'est-ce qui est inclus avec le robot ?",
         "Chaque unité est livrée avec le SDK complet et une API REST simple, un modèle URDF, un simulateur inclus, une stéréo montée sur la tête et des caméras de poignet, des préhenseurs et un support ingénierie direct. La téléopération fonctionne dès le premier jour."),
        ("Puis-je collecter des données de téléopération et entraîner des politiques moi-même ?",
         "Oui. Téléopérez en VR avec un Meta Quest 3S ou un contrôleur leader-suiveur, enregistrez des démonstrations au format de jeu de données standard, et entraînez ACT ou affinez un modèle vision-language-action sur un seul GPU grand public."),
        ("Sur quelle unité de calcul le robot fonctionne-t-il ?",
         "Le calcul embarqué est un Raspberry Pi 5 ou un NVIDIA Jetson. Les politiques légères s'exécutent sur l'appareil, tandis que les modèles vision-language-action plus lourds peuvent s'exécuter sur un GPU de station de travail relié et diffuser des commandes via l'API REST."),
        ("Le robot est-il modulaire ?",
         "Oui. Vous pouvez changer les bras, les préhenseurs (à 2 doigts, 4 doigts, ou mains avancées à cinq doigts) et les modules de base comme les jambes ou les roues, et adapter la plateforme à votre tâche plutôt que l'inverse."),
        ("Où le robot est-il fabriqué ?",
         "Prometheus est conçu et fabriqué dans l'Union européenne, ce qui compte pour les laboratoires de recherche et les entreprises européennes attachés à la provenance de la chaîne d'approvisionnement, au support et à la souveraineté des données."),
    ],
    "hr": [
        ("Koje modele umjetne inteligencije robot podržava?",
         "Odmah po isporuci podržava moderne politike vrste vizija-jezik-akcija te politike imitacijskog učenja, uključujući Pi0, Pi0.5, ACT i SmolVLA. Prikupite podatke teleoperacije, fino podesite model na potrošačkom GPU i implementirajte ga putem SDK."),
        ("Što je uključeno uz robota?",
         "Svaka jedinica isporučuje se s potpunim SDK i jednostavnim REST API, URDF modelom, ugrađenim simulatorom, stereo kamerom na glavi te kamerama na zapešću, hvataljkama i izravnom inženjerskom podrškom. Cjevovod za teleoperaciju radi već od prvog dana."),
        ("Mogu li sam prikupljati podatke teleoperacije i trenirati politike?",
         "Da. Upravljajte na daljinu putem VR uz Meta Quest 3S ili putem upravljača vođa-sljedbenik, snimajte demonstracije u standardnom formatu skupa podataka te trenirajte ACT ili fino podesite model vizija-jezik-akcija na jednom potrošačkom GPU."),
        ("Na kojem računalnom sklopu robot radi?",
         "Ugrađeno računalo je Raspberry Pi 5 ili NVIDIA Jetson. Lagane politike izvode se izravno na uređaju, dok zahtjevniji modeli vizija-jezik-akcija mogu raditi na povezanoj radnoj stanici s GPU i slati naredbe putem REST API."),
        ("Je li robot modularan?",
         "Da. Možete zamijeniti ruke, hvataljke (s dva prsta, s četiri prsta ili napredne šake s pet prstiju) te osnovne module poput nogu ili kotača, i prilagoditi platformu svojem zadatku, a ne obrnuto."),
        ("Gdje se robot proizvodi?",
         "Prometheus je projektiran i proizveden u EU, što je važno za europske istraživačke laboratorije i tvrtke kojima je stalo do podrijetla opskrbnog lanca, podrške i suverenosti podataka."),
    ],
    "hu": [
        ("Milyen MI-modelleket támogat a robot?",
         "Alapból támogatja a modern vizuális-nyelvi-cselekvési (vision-language-action) és imitációs tanulási szabályrendszereket, köztük a Pi0, Pi0.5, ACT és SmolVLA modelleket. Gyűjtsön teleoperációs adatokat, finomhangoljon egy fogyasztói GPU segítségével, majd telepítsen az SDK révén."),
        ("Mit tartalmaz a robot csomagja?",
         "Minden egység a teljes SDK csomaggal és egy egyszerű REST API felülettel, egy URDF modellel, egy beépített szimulátorral, fejre szerelt sztereó- valamint csuklókamerákkal, megfogókkal és közvetlen mérnöki támogatással érkezik. A teleoperációs munkafolyamat már az első napon működik."),
        ("Gyűjthetek-e magam teleoperációs adatokat, valamint betaníthatok-e szabályrendszereket?",
         "Igen. Teleoperáljon VR segítségével egy Meta Quest 3S eszközzel vagy egy vezető-követő (leader-follower) vezérlővel, rögzítsen bemutatókat a szabványos adathalmaz-formátumban, majd tanítsa be az ACT modellt vagy finomhangoljon egy vizuális-nyelvi-cselekvési modellt egyetlen fogyasztói GPU segítségével."),
        ("Milyen számítási egységen fut a robot?",
         "A fedélzeti számítási egység egy Raspberry Pi 5 vagy egy NVIDIA Jetson. A könnyűsúlyú szabályrendszerek az eszközön futnak, míg a nagyobb vizuális-nyelvi-cselekvési modellek egy kábellel csatlakoztatott munkaállomás GPU egységén futtathatók, és a parancsokat a REST API felületen keresztül továbbítják."),
        ("Moduláris-e a robot?",
         "Igen. Lecserélheti a karokat, a megfogókat (2 ujjas, 4 ujjas vagy fejlett ötujjas kezek), valamint az alapmodulokat, például lábakat vagy kerekeket, így a platformot a feladatához igazíthatja, nem pedig fordítva."),
        ("Hol készül a robot?",
         "A Prometheus tervezése valamint gyártása az Európai Unióban történik, ami fontos azon európai kutatólaboratóriumok és vállalatok számára, amelyeknek lényeges az ellátási lánc eredete, a támogatás, valamint az adatszuverenitás."),
    ],
    "it": [
        ("Quali modelli di intelligenza artificiale supporta il robot?",
         "Da subito supporta moderne politiche di tipo visione-linguaggio-azione e di apprendimento per imitazione, tra cui Pi0, Pi0.5, ACT e SmolVLA. Raccogliete dati di teleoperazione, eseguite il fine-tuning su una GPU consumer e procedete al deployment tramite l'SDK."),
        ("Cosa è incluso con il robot?",
         "Ogni unità viene fornita con l'SDK completo e una semplice REST API, un modello URDF, un simulatore integrato, telecamere stereo montate sulla testa più telecamere sui polsi, pinze di presa e supporto ingegneristico diretto. La pipeline di teleoperazione funziona fin dal primo giorno."),
        ("Posso raccogliere dati di teleoperazione e addestrare le politiche autonomamente?",
         "Sì. Eseguite la teleoperazione tramite VR con un Meta Quest 3S o un controller leader-follower, registrate le dimostrazioni nel formato dataset standard e addestrate ACT oppure eseguite il fine-tuning di un modello visione-linguaggio-azione su una singola GPU consumer."),
        ("Su quale potenza di calcolo opera il robot?",
         "Il calcolo a bordo è affidato a un Raspberry Pi 5 o a un NVIDIA Jetson. Le politiche leggere vengono eseguite sul dispositivo, mentre i modelli visione-linguaggio-azione più impegnativi possono essere eseguiti sulla GPU di una workstation collegata, trasmettendo i comandi tramite la REST API."),
        ("Il robot è modulare?",
         "Sì. Potete sostituire bracci, pinze di presa (a 2 dita, a 4 dita o mani avanzate a cinque dita) e moduli di base come gambe o ruote, adattando la piattaforma al vostro compito anziché il contrario."),
        ("Dove viene prodotto il robot?",
         "Prometheus è progettato e fabbricato nell'Unione Europea, un aspetto importante per i laboratori di ricerca e le aziende europee che tengono alla provenienza della catena di approvvigionamento, al supporto e alla sovranità dei dati."),
    ],
    "lt": [
        ("Kokius dirbtinio intelekto modelius palaiko robotas?",
         "Iš karto palaikomi šiuolaikiniai regos kalbos veiksmo ir imitacinio mokymosi metodai, įskaitant Pi0, Pi0.5, ACT ir SmolVLA. Surinkite teleoperavimo duomenis, tiksliai suderinkite modelį naudodami vartotojiško lygio GPU ir įdiekite per SDK."),
        ("Kas pridedama prie roboto?",
         "Kiekvienas įrenginys tiekiamas su pilnu SDK ir paprastu REST API, URDF modeliu, integruotu simuliatoriumi, ant galvos tvirtinamomis stereo bei riešo kameromis, griebtuvais ir tiesiogine inžinerine pagalba. Teleoperavimo procesas veikia jau pirmąją dieną."),
        ("Ar galiu pats rinkti teleoperavimo duomenis ir mokyti modelius?",
         "Taip. Valdykite teleoperavimą per VR su Meta Quest 3S arba vedlio sekėjo valdikliu, įrašykite demonstracijas standartiniu duomenų rinkinio formatu ir mokykite ACT arba tiksliai suderinkite regos kalbos veiksmo modelį naudodami vieną vartotojiško lygio GPU."),
        ("Kokiu skaičiavimo įrenginiu veikia robotas?",
         "Įmontuotas skaičiavimo įrenginys yra Raspberry Pi 5 arba NVIDIA Jetson. Lengvi metodai veikia pačiame įrenginyje, o sudėtingesni regos kalbos veiksmo modeliai gali veikti prijungtos darbo stoties GPU ir perduoti komandas per REST API."),
        ("Ar robotas yra modulinis?",
         "Taip. Galite keisti rankas, griebtuvus (su 2 pirštais, 4 pirštais arba pažangias penkių pirštų plaštakas) ir bazinius modulius, tokius kaip kojos ar ratai, bei pritaikyti platformą savo užduočiai, o ne atvirkščiai."),
        ("Kur pagamintas robotas?",
         "Prometheus yra suprojektuotas ir pagamintas Europos Sąjungoje, o tai svarbu Europos tyrimų laboratorijoms ir įmonėms, kurioms rūpi tiekimo grandinės kilmė, pagalba ir duomenų suverenumas."),
    ],
    "lv": [
        ("Kurus mākslīgā intelekta modeļus robots atbalsta?",
         "Jau no paša sākuma tas atbalsta mūsdienu redzes-valodas-darbības un imitācijas mācīšanās politikas, tostarp Pi0, Pi0.5, ACT un SmolVLA. Vāciet teleoperācijas datus, precīzi pielāgojiet tos patērētāju GPU un izvietojiet, izmantojot SDK."),
        ("Kas ir iekļauts robota komplektācijā?",
         "Katra vienība tiek piegādāta ar pilnu SDK un vienkāršu REST API, URDF modeli, iekļautu simulatoru, galvā stiprināmām stereo kamerām un kamerām uz plaukstas locītavām, satvērējiem un tiešu inženieru atbalstu. Teleoperācijas plūsma darbojas jau pirmajā dienā."),
        ("Vai es varu pats vākt teleoperācijas datus un apmācīt politikas?",
         "Jā. Veiciet teleoperāciju, izmantojot VR ar Meta Quest 3S vai vadītāja-sekotāja kontrolieri, ierakstiet demonstrācijas standarta datu kopas formātā un apmāciet ACT vai precīzi pielāgojiet redzes-valodas-darbības modeli ar vienu patērētāju GPU."),
        ("Uz kāda skaitļošanas aprīkojuma robots darbojas?",
         "Iebūvētā skaitļošanas vienība ir Raspberry Pi 5 vai NVIDIA Jetson. Vieglās politikas darbojas ierīcē, savukārt smagākus redzes-valodas-darbības modeļus var palaist uz pievienotas darbstacijas GPU un straumēt komandas, izmantojot REST API."),
        ("Vai robots ir modulārs?",
         "Jā. Jūs varat nomainīt rokas, satvērējus (ar 2 pirkstiem, 4 pirkstiem vai uzlabotas piecu pirkstu plaukstas) un pamatnes moduļus, piemēram, kājas vai riteņus, kā arī pielāgot platformu savam uzdevumam, nevis otrādi."),
        ("Kur robots tiek ražots?",
         "Prometheus tiek projektēts un ražots Eiropas Savienībā, kas ir svarīgi Eiropas pētniecības laboratorijām un uzņēmumiem, kuriem rūp piegādes ķēdes izcelsme, atbalsts un datu suverenitāte."),
    ],
    "nl": [
        ("Welke AI-modellen ondersteunt de robot?",
         "Standaard ondersteunt hij moderne vision-language-action- en imitatie-leerbeleid, waaronder Pi0, Pi0.5, ACT en SmolVLA. Verzamel teleoperatiegegevens, verfijn ze op een consumenten-GPU en zet ze in via de SDK."),
        ("Wat wordt er bij de robot geleverd?",
         "Elke eenheid wordt geleverd met de volledige SDK en een eenvoudige REST API, een URDF-model, een meegeleverde simulator, op het hoofd gemonteerde stereo- plus polscamera's, grijpers en directe technische ondersteuning. De teleoperatiepijplijn werkt vanaf de eerste dag."),
        ("Kan ik zelf teleoperatiegegevens verzamelen en beleid trainen?",
         "Ja. Bestuur op afstand via VR met een Meta Quest 3S of een leader-follower-controller, leg demonstraties vast in het standaard datasetformaat en train ACT of verfijn een vision-language-action-model op een enkele consumenten-GPU."),
        ("Op welke rekenkracht draait de robot?",
         "De ingebouwde rekenkracht is een Raspberry Pi 5 of een NVIDIA Jetson. Lichtgewicht beleid draait op het apparaat zelf, terwijl zwaardere vision-language-action-modellen op een aangesloten werkstation-GPU kunnen draaien en commando's via de REST API kunnen versturen."),
        ("Is de robot modulair?",
         "Ja. U kunt armen, grijpers (2-vinger, 4-vinger of geavanceerde vijfvingerhanden) en basismodules zoals poten of wielen verwisselen, en het platform aanpassen aan uw taak in plaats van andersom."),
        ("Waar wordt de robot gemaakt?",
         "Prometheus wordt ontworpen en geproduceerd in de Europese Unie, wat van belang is voor Europese onderzoekslaboratoria en bedrijven die waarde hechten aan de herkomst van de toeleveringsketen, ondersteuning en datasoevereiniteit."),
    ],
    "no": [
        ("Hvilke AI-modeller støtter roboten?",
         "Rett ut av esken støtter den moderne policyer for visjon-språk-handling og imitasjonslæring, inkludert Pi0, Pi0.5, ACT og SmolVLA. Samle inn teleoperasjonsdata, finjuster på en GPU for forbrukermarkedet, og distribuer via SDK."),
        ("Hva følger med roboten?",
         "Hver enhet leveres med komplett SDK og et enkelt REST API, en URDF-modell, en medfølgende simulator, hodemonterte stereokameraer pluss håndleddskameraer, gripere og direkte ingeniørstøtte. Teleoperasjonsløypen fungerer fra dag én."),
        ("Kan jeg samle inn teleoperasjonsdata og trene policyer selv?",
         "Ja. Teleoperer via VR med en Meta Quest 3S eller en leder-følger-kontroller, ta opp demonstrasjoner i standard datasettformat, og tren ACT eller finjuster en visjon-språk-handling-modell på én enkelt GPU for forbrukermarkedet."),
        ("Hvilken beregningskraft kjører roboten på?",
         "Beregningskraften om bord er en Raspberry Pi 5 eller en NVIDIA Jetson. Lette policyer kjører på enheten, mens tyngre visjon-språk-handling-modeller kan kjøre på en tilkoblet arbeidsstasjons-GPU og strømme kommandoer over REST API."),
        ("Er roboten modulær?",
         "Ja. Du kan bytte ut armer, gripere (2-finger, 4-finger eller avanserte femfingerhender) og basismoduler som ben eller hjul, og tilpasse plattformen til oppgaven din i stedet for omvendt."),
        ("Hvor er roboten produsert?",
         "Prometheus er designet og produsert i Den europeiske union, noe som er viktig for europeiske forskningslaboratorier og selskaper som bryr seg om forsyningskjedens opprinnelse, støtte og datasuverenitet."),
    ],
    "pl": [
        ("Które modele AI obsługuje robot?",
         "Bezpośrednio po uruchomieniu obsługuje nowoczesne polityki typu wizja-język-działanie oraz uczenia przez naśladowanie, w tym Pi0, Pi0.5, ACT i SmolVLA. Zbieraj dane z teleoperacji, dostrajaj je na konsumenckim GPU i wdrażaj poprzez SDK."),
        ("Co jest dołączone do robota?",
         "Każda jednostka dostarczana jest z pełnym SDK i prostym REST API, modelem URDF, dołączonym symulatorem, montowanymi na głowie kamerami stereo oraz kamerami nadgarstkowymi, chwytakami i bezpośrednim wsparciem inżynieryjnym. Potok teleoperacji działa od pierwszego dnia."),
        ("Czy mogę samodzielnie zbierać dane z teleoperacji i trenować polityki?",
         "Tak. Prowadź teleoperację za pomocą VR z Meta Quest 3S lub kontrolera typu leader-follower, rejestruj demonstracje w standardowym formacie zbioru danych oraz trenuj ACT albo dostrajaj model wizja-język-działanie na pojedynczym konsumenckim GPU."),
        ("Na jakim sprzęcie obliczeniowym działa robot?",
         "Pokładowa jednostka obliczeniowa to Raspberry Pi 5 lub NVIDIA Jetson. Lekkie polityki działają bezpośrednio na urządzeniu, natomiast cięższe modele wizja-język-działanie mogą działać na podłączonej stacji roboczej z GPU i przesyłać polecenia poprzez REST API."),
        ("Czy robot jest modularny?",
         "Tak. Możesz wymieniać ramiona, chwytaki (dwupalczaste, czteropalczaste lub zaawansowane pięciopalczaste dłonie) oraz moduły bazowe, takie jak nogi czy koła, i dostosowywać platformę do swojego zadania, a nie odwrotnie."),
        ("Gdzie produkowany jest robot?",
         "Prometheus jest projektowany i produkowany w Unii Europejskiej, co ma znaczenie dla europejskich laboratoriów badawczych i firm, które dbają o pochodzenie łańcucha dostaw, wsparcie oraz suwerenność danych."),
    ],
    "ro": [
        ("Ce modele de inteligență artificială acceptă robotul?",
         "Din configurația standard acceptă politici moderne de tip vision-language-action și de învățare prin imitație, inclusiv Pi0, Pi0.5, ACT și SmolVLA. Colectați date de teleoperare, efectuați ajustarea fină pe un GPU de consum și implementați prin SDK."),
        ("Ce este inclus împreună cu robotul?",
         "Fiecare unitate este livrată cu SDK-ul complet și un REST API simplu, un model URDF, un simulator inclus, camere stereo montate pe cap plus camere pe încheietură, dispozitive de prindere și asistență tehnică directă. Fluxul de teleoperare funcționează din prima zi."),
        ("Pot să colectez date de teleoperare și să antrenez eu însumi politici?",
         "Da. Teleoperați prin VR cu un Meta Quest 3S sau un controler de tip lider-urmăritor, înregistrați demonstrații în formatul standard al setului de date și antrenați ACT sau efectuați ajustarea fină a unui model vision-language-action pe un singur GPU de consum."),
        ("Pe ce capacitate de calcul rulează robotul?",
         "Capacitatea de calcul de la bord este un Raspberry Pi 5 sau un NVIDIA Jetson. Politicile ușoare rulează direct pe dispozitiv, în timp ce modelele vision-language-action mai solicitante pot rula pe GPU-ul unei stații de lucru conectate și pot transmite comenzi prin REST API."),
        ("Robotul este modular?",
         "Da. Puteți schimba brațele, dispozitivele de prindere (cu 2 degete, 4 degete sau mâini avansate cu cinci degete) și modulele de bază, precum picioare sau roți, adaptând platforma la sarcina dumneavoastră, și nu invers."),
        ("Unde este fabricat robotul?",
         "Prometheus este proiectat și fabricat în Uniunea Europeană, ceea ce contează pentru laboratoarele de cercetare și companiile europene preocupate de proveniența lanțului de aprovizionare, de asistență și de suveranitatea datelor."),
    ],
    "sk": [
        ("Ktoré modely umelej inteligencie robot podporuje?",
         "Hneď po vybalení podporuje moderné politiky typu vízia-jazyk-akcia a politiky napodobňovacieho učenia vrátane Pi0, Pi0.5, ACT a SmolVLA. Zbierajte údaje z teleoperácie, doladujte ich na bežnom spotrebiteľskom GPU a nasaďte ich prostredníctvom SDK."),
        ("Čo je súčasťou robota?",
         "Každá jednotka sa dodáva s kompletným SDK a jednoduchým REST API, modelom URDF, integrovaným simulátorom, stereo kamerou na hlave aj kamerami na zápästí, chápadlami a priamou inžinierskou podporou. Proces teleoperácie funguje hneď od prvého dňa."),
        ("Môžem si sám zbierať údaje z teleoperácie a trénovať politiky?",
         "Áno. Teleoperujte cez VR pomocou zariadenia Meta Quest 3S alebo ovládača typu vedúci-nasledovník, zaznamenávajte ukážky v štandardnom formáte množiny údajov a trénujte ACT alebo doladzujte model typu vízia-jazyk-akcia na jedinom spotrebiteľskom GPU."),
        ("Na akom výpočtovom výkone robot beží?",
         "Palubným výpočtovým výkonom je Raspberry Pi 5 alebo NVIDIA Jetson. Nenáročné politiky bežia priamo v zariadení, zatiaľ čo náročnejšie modely typu vízia-jazyk-akcia môžu bežať na pripojenej pracovnej stanici s GPU a posielať príkazy cez REST API."),
        ("Je robot modulárny?",
         "Áno. Môžete vymieňať ramená, chápadlá (dvojprstové, štvorprstové alebo pokročilé päťprstové ruky) a základné moduly, ako sú nohy alebo kolesá, a prispôsobiť platformu svojej úlohe namiesto opačného postupu."),
        ("Kde sa robot vyrába?",
         "Prometheus je navrhnutý a vyrábaný v Európskej únii, čo má význam pre európske výskumné laboratóriá a spoločnosti, ktorým záleží na pôvode dodávateľského reťazca, podpore a suverenite údajov."),
    ],
    "sl": [
        ("Katere modele umetne inteligence robot podpira?",
         "Že takoj po namestitvi podpira sodobne politike vida-jezika-akcije in posnemovalnega učenja, vključno s Pi0, Pi0.5, ACT in SmolVLA. Zbirajte podatke teleoperacije, izvedite fino prilagajanje na potrošniškem GPU in jih namestite prek SDK."),
        ("Kaj je vključeno z robotom?",
         "Vsaka enota je dobavljena s celotnim SDK in preprostim REST API, modelom URDF, priloženim simulatorjem, stereo kamerami na glavi ter kamerami na zapestju, prijemali in neposredno inženirsko podporo. Cevovod teleoperacije deluje že prvi dan."),
        ("Ali lahko sam zbiram podatke teleoperacije in učim politike?",
         "Da. Teleoperirajte prek VR z napravo Meta Quest 3S ali s krmilnikom vodja-sledilec, snemajte demonstracije v standardni obliki nabora podatkov ter učite ACT ali fino prilagodite model vida-jezika-akcije na enem samem potrošniškem GPU."),
        ("Na kakšni računski opremi robot teče?",
         "Vgrajena računska enota je Raspberry Pi 5 ali NVIDIA Jetson. Lahke politike tečejo na napravi sami, medtem ko lahko težji modeli vida-jezika-akcije tečejo na povezani delovni postaji z GPU in prenašajo ukaze prek REST API."),
        ("Ali je robot modularen?",
         "Da. Zamenjate lahko roke, prijemala (z dvema prstoma, štirimi prsti ali napredne roke s petimi prsti) ter osnovne module, kot so noge ali kolesa, in platformo prilagodite svoji nalogi, namesto da bi bilo obratno."),
        ("Kje je robot izdelan?",
         "Prometheus je zasnovan in izdelan v Evropski uniji, kar je pomembno za evropske raziskovalne laboratorije in podjetja, ki jim je mar za izvor dobavne verige, podporo in suverenost podatkov."),
    ],
    "sv": [
        ("Vilka AI-modeller stödjer roboten?",
         "Direkt ur lådan stödjer den moderna policyer för vision-language-action och imitationsinlärning, inklusive Pi0, Pi0.5, ACT och SmolVLA. Samla in teleoperationsdata, finjustera på en konsument-GPU och driftsätt via SDK."),
        ("Vad ingår med roboten?",
         "Varje enhet levereras med den fullständiga SDK och ett enkelt REST API, en URDF-modell, en medföljande simulator, huvudmonterade stereokameror samt handledskameror, gripdon och direkt teknisk support. Teleoperationsflödet fungerar från första dagen."),
        ("Kan jag samla in teleoperationsdata och träna policyer själv?",
         "Ja. Teleoperera via VR med en Meta Quest 3S eller en ledare-följare-styrenhet, spela in demonstrationer i standardformatet för dataset och träna ACT eller finjustera en vision-language-action-modell på en enda konsument-GPU."),
        ("Vilken beräkningskraft körs roboten på?",
         "Den inbyggda beräkningskraften är en Raspberry Pi 5 eller en NVIDIA Jetson. Lättviktiga policyer körs på enheten, medan tyngre vision-language-action-modeller kan köras på en ansluten arbetsstations-GPU och strömma kommandon via REST API."),
        ("Är roboten modulär?",
         "Ja. Du kan byta ut armar, gripdon (med 2 fingrar, 4 fingrar eller avancerade femfingerhänder) och basmoduler såsom ben eller hjul, och anpassa plattformen till din uppgift i stället för tvärtom."),
        ("Var tillverkas roboten?",
         "Prometheus är designad och tillverkad i Europeiska unionen, vilket är viktigt för europeiska forskningslaboratorier och företag som bryr sig om härkomst i leveranskedjan, support och datasuveränitet."),
    ],
}
